<?php include  "includes/head.php";?>
<?php include "includes/nav.php";?>
<?php include "includes/header.php";?>
<?php include "includes/toucheader.php";?>
<?php include "includes/aboutsection.php";?>
<?php include "includes/servicessection.php";?>
<?php include "includes/gallerysection.php";?>
<?php include "includes/testimonialsection.php";?>
<?php include "includes/contactsection.php";?>
<?php include "includes/footer.php";?>